
server.port: 7777

mdx:
  weight:
    memory: 0.5
    query: 0.5
  cacheTime: 600
  proxy:
    - mdx-ke4:
      type: mdx
      host: 10.211.55.2:7777
#      config:
#        connect_timeout: 30s
#        proxy_send_timeout: 1800s
#        proxy_read_timeout: 1800s
      servers:
        - 127.0.0.1:7080
        - 127.0.0.1:7081

spring:
  application:
    name: kylin-gateway
  jmx:
    enabled: false
  cloud:
    gateway:
      loadbalancer:
        use404: false
        queryRouteDefault: ${kylin.gateway.route.query-route-default}
      httpclient:
        connectTimeout: 15000
        responseTimeout: 480000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

server:
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      buffered: true
      directory: logs
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t \"%r\" %s %b %D %{User-Agent}i"
      rotate: true
      rename-on-rotate: false
      prefix: access_log
      suffix: .log

kylin:
  gateway:
    route:
      refresh-cron: 0/3 * * * * *
      query-route-default: true
      refresh-interval: 3s
    ke:
      version: mdx
    health:
      check-url: /api/system/health
      load_url: /api/system/load
      rest-template:
        connect-timeout: 1500
        read-timeout: 5000
      ping-strategy:
        retry-times: 3
        interval-seconds: 3
    datasource:
      type: config
      route-table-file-path: ${gateway.home}/conf/route_table
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.3.1.17:3306/leotest
      username: root
      password: passw0rd
      table-name: km_route_table

management.endpoints.web.exposure.include: health, gateway
